# -*- coding: utf-8 -*-
"""main_hypnos_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HezQt7oBjQd-Vui7XxUZA9X6f-eG60g
"""

# -*- coding: utf-8 -*-
"""
================================================================================
PROYECTO HYPNOS-ENS: ESTIMACIÓN DE PROFUNDIDAD ANESTÉSICA (PSI)
================================================================================
Arquitectura: Multitask GRU (Regresión + Clasificación de Tendencia)
================================================================================
"""

import os
import random
import json
import pickle
import datetime
import platform
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de Determinismo para reproducibilidad total
os.environ['TF_DETERMINISTIC_OPS']      = '1'
os.environ['CUBLAS_WORKSPACE_CONFIG']   = ':4096:8'
os.environ['PYTHONHASHSEED']            = '42'
os.environ['TF_CPP_MIN_LOG_LEVEL']      = '2'

import tensorflow as tf
from tensorflow.keras import mixed_precision
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Dense, Dropout, BatchNormalization,
                                     Input, GRU, Concatenate, Lambda)
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import (mean_absolute_error, r2_score,
                             accuracy_score, classification_report,
                             confusion_matrix, f1_score,
                             balanced_accuracy_score)

# Configuración de precisión mixta para GPUs modernas (si está disponible)
try:
    mixed_precision.set_global_policy('mixed_bfloat16')
    print(f"✅ Política de precisión: {mixed_precision.global_policy().name}")
except Exception as e:
    print(f"⚠️ No se pudo establecer bfloat16 ({e}), usando precisión estándar.")

# ==============================================================================
# CONFIGURACIÓN GLOBAL Y RUTAS
# ==============================================================================
# Ajustado para ejecución local: Crea una carpeta 'datos' junto al script
RUTA_BASE     = './datos/'
ARCHIVO       = os.path.join(RUTA_BASE, 'Base_Maestra_ESTADISTICA_HONESTA_CLEAN.csv')
CARPETA_FINAL = './resultados/Graficas_Quimera_V5_MSE/'
os.makedirs(CARPETA_FINAL, exist_ok=True)

TIMESTEPS        = 120    # 10 minutos de contexto a 0.2 Hz
HORIZONTE        = 6      # 30 seg hacia el futuro
UMBRAL_TENDENCIA = 3      # 3 PSI en 30 seg
SEMILLA          = 42
BATCH_SIZE       = 8192
N_RUNS           = 10

def configurar_semilla(s: int):
    """Fija todas las fuentes de aleatoriedad para reproducibilidad total."""
    os.environ['PYTHONHASHSEED'] = str(s)
    random.seed(s)
    np.random.seed(s)
    tf.random.set_seed(s)

configurar_semilla(SEMILLA)

# ==============================================================================
# DEFINICIÓN DE FEATURES
# ==============================================================================
FEATURES_DEMOGRAFICAS = ['PESO', 'SEXO_NUM']
FEATURES_HEMODINAMICAS = ['FC', 'PSIS', 'PDIA', 'FC_vel', 'FC_trend_3min']
FEATURES_PK = ['EFF', 'EFF2', 'DOSIS_PROP_PASO', 'DOSIS_PROP_ACUM_KG', 'INF_dir4', 'INF2_dir4']
FEATURES_INTENCION = ['TARGET', 'TARGET2', 'TARGET_vel']
FEATURES_DERIVADAS_EFF = [
    'EFF_vel', 'EFF_trend_3min', 'EFF2_trend_3min', 'EFF_ratio',
    'EFF_auc_5min', 'EFF2_auc_5min', 'EFF_caida_pico', 'EFF2_caida_pico'
]

FEATURES_V5 = (FEATURES_DEMOGRAFICAS + FEATURES_HEMODINAMICAS +
               FEATURES_PK + FEATURES_INTENCION + FEATURES_DERIVADAS_EFF)

FEATURES_CON_FC_VEL = FEATURES_V5
FEATURES_BASE = ['EDAD', 'PESO', 'ESTATURA', 'SEXO_NUM',
                 'FC', 'PAM', 'INF', 'INF2', 'EFF', 'EFF2']

COLUMNA_TIEMPO = 'INDEX'

# ==============================================================================
# CLASES Y FUNCIONES DE APOYO (LOSS, EARLY STOPPING)
# ==============================================================================
class FocalLoss(tf.keras.losses.Loss):
    """Focal Loss con reduction=NONE para compatibilidad Keras 3 multi-output."""
    def __init__(self, gamma: float = 3.0, name: str = 'focal_loss'):
        super().__init__(reduction=tf.keras.losses.Reduction.NONE, name=name)
        self.gamma = gamma

    def call(self, y_true, y_pred):
        y_true    = tf.cast(tf.reshape(y_true, [-1]), tf.int32)
        y_pred    = tf.cast(y_pred, tf.float32)
        y_pred    = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)
        ce        = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
        y_true_oh = tf.one_hot(y_true, depth=tf.shape(y_pred)[-1])
        p_t       = tf.reduce_sum(y_pred * y_true_oh, axis=-1)
        return tf.pow(1.0 - p_t, self.gamma) * ce

    def get_config(self):
        return {'gamma': self.gamma}

class MacroF1EarlyStopping(tf.keras.callbacks.Callback):
    """Early stopping por macro-F1 evaluando tensor pre-cargado."""
    def __init__(self, X_val, y_val, patience=5):
        super().__init__()
        self.X_val_tensor = tf.constant(X_val.astype(np.float32))
        self.y_val        = y_val
        self.patience     = patience
        self.best_f1      = -np.inf
        self.wait         = 0
        self.best_weights = None
        self.stopped_epoch = 0

    def on_epoch_end(self, epoch, logs=None):
        preds  = self.model(self.X_val_tensor, training=False)
        y_pred = np.argmax(tf.cast(preds[1], tf.float32).numpy(), axis=1)
        f1 = f1_score(self.y_val, y_pred, average='macro', zero_division=0)
        if logs is not None:
            logs['val_macro_f1'] = f1
        if f1 > self.best_f1:
            self.best_f1      = f1
            self.wait         = 0
            self.best_weights = self.model.get_weights()
        else:
            self.wait += 1
            if self.wait >= self.patience:
                self.stopped_epoch    = epoch
                self.model.stop_training = True
                if self.best_weights is not None:
                    self.model.set_weights(self.best_weights)

    def get_best_f1(self):
        return self.best_f1

# ==============================================================================
# PREPROCESAMIENTO Y DATASETS
# ==============================================================================
def _limpiar(X):
    return np.nan_to_num(X.astype(np.float64), nan=0.0, posinf=0.0, neginf=0.0)

def escalar_fold(X_tr, X_vl):
    X_tr = _limpiar(X_tr); X_vl = _limpiar(X_vl)
    scalers  = {}
    n_tr, ts, nf = X_tr.shape
    n_vl         = X_vl.shape[0]
    for i in range(nf):
        scalers[i] = RobustScaler()
        tr_flat    = X_tr[:, :, i].reshape(-1, 1)
        vl_flat    = X_vl[:, :, i].reshape(-1, 1)
        scalers[i].fit(tr_flat)
        X_tr[:, :, i] = scalers[i].transform(tr_flat).reshape(n_tr, ts)
        X_vl[:, :, i] = scalers[i].transform(vl_flat).reshape(n_vl, ts)
    return X_tr, X_vl, scalers

def escalar_externo(X, scalers):
    X = _limpiar(X)
    n, ts, nf = X.shape
    for i in range(nf):
        feat       = X[:, :, i].reshape(-1, 1)
        X[:, :, i] = scalers[i].transform(feat).reshape(n, ts)
    return X

def ajustar_y_escalar(X):
    X = _limpiar(X)
    scalers  = {}
    n, ts, nf = X.shape
    for i in range(nf):
        scalers[i] = RobustScaler()
        feat       = X[:, :, i].reshape(-1, 1)
        scalers[i].fit(feat)
        X[:, :, i] = scalers[i].transform(feat).reshape(n, ts)
    return X, scalers

def crear_dataset_tf(X: np.ndarray, y_reg: np.ndarray, y_tend: np.ndarray,
                     weights: np.ndarray = None, batch_size: int = BATCH_SIZE,
                     shuffle: bool = True) -> tf.data.Dataset:
    outputs = {
        'out_regresion':    y_reg.astype(np.float32),
        'out_clasificacion': y_tend.astype(np.int32),
    }
    if weights is not None:
        ds = tf.data.Dataset.from_tensor_slices((X.astype(np.float32), outputs, weights.astype(np.float32)))
    else:
        ds = tf.data.Dataset.from_tensor_slices((X.astype(np.float32), outputs))

    if shuffle:
        ds = ds.shuffle(buffer_size=min(len(X), 50_000), seed=SEMILLA, reshuffle_each_iteration=True)
    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)

def filtrar_mantenimiento_redundante(df_train: pd.DataFrame, umbral_var: float = 1.0, ventana: int = 12) -> pd.DataFrame:
    def _filtrar_paciente(grupo):
        fase = grupo['FASE_PROXY'].values
        psi  = grupo['PSI'].values
        eff  = grupo['EFF'].values
        mantener = np.ones(len(grupo), dtype=bool)
        for i in range(len(grupo)):
            if fase[i] == 'Mantenimiento':
                inicio   = max(0, i - ventana)
                var_local = np.var(psi[inicio:i+1]) + np.var(eff[inicio:i+1])
                if var_local < umbral_var:
                    mantener[i] = False
        return grupo[mantener]

    df_filtrado = df_train.groupby('ID_ANONIMO', group_keys=False).apply(_filtrar_paciente).reset_index(drop=True)
    return df_filtrado

def calcular_pesos_psi_clinico(yr_norm, psi_mean, psi_std):
    psi_real = yr_norm * psi_std + psi_mean
    pesos = np.where(psi_real >= 50.0, 2.0,
            np.where(psi_real >= 25.0, 1.5,
            np.where(psi_real <  25.0, 1.2, 1.0)))
    return pesos.astype(np.float32)

def agregar_features_eff(grupo: pd.DataFrame) -> pd.DataFrame:
    df = grupo.copy()
    df['PRESION_PULSO'] = (df['PSIS'] - df['PDIA'] if ('PSIS' in df.columns and 'PDIA' in df.columns) else 0.0)
    df['FC_vel'] = df['FC'].diff().fillna(0)
    df['FC_trend_3min'] = df['FC'].rolling(36, min_periods=1).apply(lambda x: x.iloc[-1] - x.iloc[0], raw=False)

    DT_SEG = 5.0
    df['INF']  = df['INF'].fillna(0)
    df['INF2'] = df['INF2'].fillna(0)
    peso_safe  = np.where(df['PESO'].values > 0, df['PESO'].values, 70.0)

    df['DOSIS_PROP_PASO'] = (df['INF'] / 3600.0) * DT_SEG * 10.0
    if 'DILUCION_2' in df.columns:
        df['DOSIS_REMI_PASO'] = (df['INF2'] / 3600.0) * DT_SEG * df['DILUCION_2']
    else:
        df['DOSIS_REMI_PASO'] = (df['INF2'] / 3600.0) * DT_SEG

    df['DOSIS_PROP_ACUM_KG'] = df['DOSIS_PROP_PASO'].rolling(60, min_periods=1).sum() / peso_safe
    df['DOSIS_REMI_ACUM_KG'] = df['DOSIS_REMI_PASO'].rolling(60, min_periods=1).sum() / peso_safe

    df['INF_vel']  = df['INF'].diff().fillna(0)
    df['INF2_vel'] = df['INF2'].diff().fillna(0)

    def _estado_bomba(vel, inf):
        return np.where(inf == 0, -2, np.where(vel > 0, 1, np.where(vel < 0, -1, 0))).astype(np.float32)

    df['INF_dir4']  = _estado_bomba(df['INF_vel'].values,  df['INF'].values)
    df['INF2_dir4'] = _estado_bomba(df['INF2_vel'].values, df['INF2'].values)

    if 'TARGET' in df.columns:
        df['ERROR_TCI']  = df['TARGET']  - df['EFF']
        df['TARGET_vel'] = df['TARGET'].diff().fillna(0)
    else:
        df['ERROR_TCI'] = df['TARGET_vel'] = 0.0

    if 'TARGET2' in df.columns:
        df['ERROR_TCI2']  = df['TARGET2'] - df['EFF2']
        df['TARGET2_vel'] = df['TARGET2'].diff().fillna(0)
    else:
        df['ERROR_TCI2'] = df['TARGET2_vel'] = 0.0

    df['EFF_vel']  = df['EFF'].diff().fillna(0)
    df['EFF2_vel'] = df['EFF2'].diff().fillna(0)
    df['EFF_acel']  = df['EFF_vel'].diff().fillna(0)
    df['EFF2_acel'] = df['EFF2_vel'].diff().fillna(0)

    df['EFF_trend_3min']  = df['EFF'].rolling(36, min_periods=1).apply(lambda x: x.iloc[-1] - x.iloc[0], raw=False)
    df['EFF2_trend_3min'] = df['EFF2'].rolling(36, min_periods=1).apply(lambda x: x.iloc[-1] - x.iloc[0], raw=False)
    df['EFF_ratio'] = df['EFF'] / (df['EFF2'] + 0.01)
    df['EFF_auc_5min']  = df['EFF'].rolling(60,  min_periods=1).mean()
    df['EFF2_auc_5min'] = df['EFF2'].rolling(60, min_periods=1).mean()
    df['EFF_caida_pico']  = df['EFF'].rolling(120, min_periods=1).max() - df['EFF']
    df['EFF2_caida_pico'] = df['EFF2'].rolling(120, min_periods=1).max() - df['EFF2']

    return df

def crear_secuencias_paciente(grupo, lista_features):
    vals  = grupo[lista_features].values
    psi   = grupo['PSI'].values
    fases = grupo['FASE_PROXY'].values
    X_seq, y_reg, y_tend, phase_seq = [], [], [], []

    for i in range(len(grupo) - TIMESTEPS - HORIZONTE):
        X_seq.append(vals[i: i + TIMESTEPS])
        psi_actual = psi[i + TIMESTEPS - 1]
        y_reg.append(psi_actual)
        psi_futuro = psi[i + TIMESTEPS + HORIZONTE - 1]
        delta = psi_futuro - psi_actual
        if delta > UMBRAL_TENDENCIA:
            y_tend.append(2)
        elif delta < -UMBRAL_TENDENCIA:
            y_tend.append(0)
        else:
            y_tend.append(1)
        phase_seq.append(fases[i + TIMESTEPS - 1])

    return X_seq, y_reg, y_tend, phase_seq

def construir_dataset(df_in, lista_features):
    X_all, yr_all, yt_all, gr_all, ph_all = [], [], [], [], []
    for pid, grupo in df_in.groupby('ID_ANONIMO'):
        if len(grupo) > TIMESTEPS + HORIZONTE:
            Xs, yr, yt, ph = crear_secuencias_paciente(grupo, lista_features)
            X_all.extend(Xs);  yr_all.extend(yr)
            yt_all.extend(yt); ph_all.extend(ph)
            gr_all.extend([pid] * len(Xs))
    return (np.array(X_all), np.array(yr_all), np.array(yt_all), np.array(gr_all), np.array(ph_all))

def calcular_metricas_pk(y_real, y_pred, limite=10.0):
    pe     = ((y_pred - y_real) / (y_real + 1e-8)) * 100.0
    ape    = np.abs(pe)
    mdpe   = np.median(pe)
    mdape  = np.median(ape)
    wobble = np.median(np.abs(pe - mdpe))
    pct    = np.mean(np.abs(y_pred - y_real) <= limite) * 100.0
    rmse   = np.sqrt(np.mean((y_pred - y_real)**2))
    return {
        'MAE':              mean_absolute_error(y_real, y_pred),
        'RMSE':             rmse,
        'R2':               r2_score(y_real, y_pred),
        'MDPE (%)':         mdpe,
        'MDAPE (%)':        mdape,
        'Wobble (%)':       wobble,
        f'% ±{limite:.0f} PSI': pct,
    }

# ==============================================================================
# ARQUITECTURA: GRU + Gating reg→cls
# ==============================================================================
def build_chimera_model(timesteps, n_features):
    entradas = Input(shape=(timesteps, n_features))
    x = GRU(128, return_sequences=True, activation='tanh',
             recurrent_dropout=0.05, name='gru_1', dtype='float32')(entradas)
    x = GRU(64,  return_sequences=False, activation='tanh',
             recurrent_dropout=0.05, name='gru_2', dtype='float32')(x)
    x = BatchNormalization(name='bn_shared')(x)
    x = Dropout(0.3)(x)
    x = Dense(64, activation='swish', name='dense_shared')(x)

    reg     = Dense(32, activation='swish', name='dense_reg')(x)
    out_reg = Dense(1, activation='linear', name='out_regresion', dtype='float32')(reg)

    psi_hat_sg = Lambda(lambda t: tf.stop_gradient(tf.cast(t, tf.float32)), name='stop_gradient')(out_reg)
    x_cond  = Concatenate(name='concat_reg_cls')([x, psi_hat_sg])
    cls     = Dense(32, activation='swish', name='dense_cls')(x_cond)
    out_cls = Dense(3, activation='softmax', name='out_clasificacion', dtype='float32')(cls)

    return Model(inputs=entradas, outputs=[out_reg, out_cls])

def compilar_fase1(model):
    for capa in ['dense_cls', 'out_clasificacion']:
        model.get_layer(capa).trainable = False
    lr = tf.keras.optimizers.schedules.CosineDecay(0.002, 20000, alpha=0.01)
    model.compile(
        optimizer=tf.keras.optimizers.AdamW(lr, weight_decay=1e-4),
        loss={'out_regresion': tf.keras.losses.MeanSquaredError(), 'out_clasificacion': FocalLoss(gamma=3.0)},
        loss_weights={'out_regresion': 1.0, 'out_clasificacion': 0.0},
        metrics={'out_regresion': 'mae', 'out_clasificacion': 'accuracy'},
        jit_compile="auto")
    return model

def compilar_fase2(model):
    for layer in model.layers:
        layer.trainable = True
    for capa in ['gru_1', 'gru_2', 'bn_shared', 'dense_shared', 'dense_reg']:
        model.get_layer(capa).trainable = False
    lr = tf.keras.optimizers.schedules.CosineDecay(0.0005, 12000, alpha=0.01)
    model.compile(
        optimizer=tf.keras.optimizers.AdamW(lr, weight_decay=1e-4),
        loss={'out_regresion': tf.keras.losses.MeanSquaredError(), 'out_clasificacion': FocalLoss(gamma=3.0)},
        loss_weights={'out_regresion': 0.0, 'out_clasificacion': 1.0},
        metrics={'out_regresion': 'mae', 'out_clasificacion': 'accuracy'},
        jit_compile="auto")
    return model

def oversample_clases_minoritarias(X_tr, yr_tr, yt_tr, factor=4):
    idx_est  = np.where(yt_tr == 1)[0]
    idx_desc = np.tile(np.where(yt_tr == 0)[0], factor)
    idx_asc  = np.tile(np.where(yt_tr == 2)[0], factor)
    idx      = np.concatenate([idx_est, idx_desc, idx_asc])
    np.random.shuffle(idx)
    return X_tr[idx], yr_tr[idx], yt_tr[idx]

def balancear_fases(X_tr, yr_tr, yt_tr, phases_tr, ratio_max_mantenimiento=0.55):
    idx_mant  = np.where(phases_tr == 'Mantenimiento')[0]
    idx_otras = np.where(phases_tr != 'Mantenimiento')[0]
    n_otras   = len(idx_otras)
    n_max     = min(int(n_otras * ratio_max_mantenimiento / (1 - ratio_max_mantenimiento)), len(idx_mant))
    idx_sub   = np.random.choice(idx_mant, n_max, replace=False)
    idx_fin   = np.concatenate([idx_otras, idx_sub])
    np.random.shuffle(idx_fin)
    return (X_tr[idx_fin], yr_tr[idx_fin], yt_tr[idx_fin], phases_tr[idx_fin])

N_MC_MUESTRAS = 50

def predecir_con_incertidumbre(model, X, n_muestras=N_MC_MUESTRAS):
    X_tensor = tf.constant(X.astype(np.float32))
    psi_muestras, tend_muestras = [], []
    for _ in range(n_muestras):
        psi_n, tend_p = model(X_tensor, training=True)
        psi_muestras.append(np.nan_to_num(tf.cast(psi_n, tf.float32).numpy().flatten(), nan=0.0))
        tend_muestras.append(np.nan_to_num(tf.cast(tend_p, tf.float32).numpy(), nan=0.0))
    psi_arr  = np.array(psi_muestras)
    tend_arr = np.array(tend_muestras)
    return psi_arr.mean(axis=0), psi_arr.std(axis=0), tend_arr.mean(axis=0)

# ==============================================================================
# PIPELINE DE EXPERIMENTO
# ==============================================================================
def run_experimento(features_list: list, label: str, df_cv_in: pd.DataFrame, df_holdout_in: pd.DataFrame, carpeta: str) -> dict:
    print(f"\n{'='*70}\n🧪 EXPERIMENTO {label} — {len(features_list)} features\n{'='*70}")

    X, y_reg, y_tend, groups, phases = construir_dataset(df_cv_in, features_list)

    n_bad = (~np.isfinite(X)).sum()
    if n_bad > 0:
        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

    gkf = GroupKFold(n_splits=5)
    y_reg_pred_cv, y_tend_pred_cv = np.zeros_like(y_reg), np.zeros_like(y_tend)
    fold_models, historiales, epocas_f1_cv, epocas_f2_cv, resultados_folds = [], [], [], [], []

    for fold, (train_idx, val_idx) in enumerate(gkf.split(X, y_reg, groups), start=1):
        print(f"\n   🔄 Fold {fold}/5")
        X_train, X_val = X[train_idx].copy(), X[val_idx].copy()
        yr_train, yr_val = y_reg[train_idx],  y_reg[val_idx]
        yt_train, yt_val = y_tend[train_idx], y_tend[val_idx]

        X_train, X_val, scalers_fold = escalar_fold(X_train, X_val)

        psi_mean = yr_train.mean()
        psi_std  = yr_train.std() + 1e-8
        yr_train_norm = (yr_train - psi_mean) / psi_std
        yr_val_norm   = (yr_val   - psi_mean) / psi_std

        phases_train = phases[train_idx]
        (X_train, yr_train_norm, yt_train, phases_train) = balancear_fases(X_train, yr_train_norm, yt_train, phases_train, 0.55)

        combined_w = calcular_pesos_psi_clinico(yr_train_norm, psi_mean, psi_std)

        # Fase 1
        model = build_chimera_model(TIMESTEPS, len(features_list))
        model = compilar_fase1(model)
        es_f1 = EarlyStopping(monitor='val_out_regresion_mae', patience=5, restore_best_weights=True, mode='min')

        ds_tr_f1 = crear_dataset_tf(X_train, yr_train_norm, yt_train, weights=combined_w, shuffle=True)
        ds_vl    = crear_dataset_tf(X_val, yr_val_norm, yt_val, shuffle=False)
        hist_f1  = model.fit(ds_tr_f1, validation_data=ds_vl, epochs=20, callbacks=[es_f1], verbose=0)
        epocas_f1_cv.append(len(hist_f1.history['loss']))

        # Fase 2
        model = compilar_fase2(model)
        X_os, yr_os, yt_os = oversample_clases_minoritarias(X_train, yr_train_norm, yt_train, factor=4)
        cb_f2    = MacroF1EarlyStopping(X_val, yt_val, patience=8)
        ds_os    = crear_dataset_tf(X_os, yr_os, yt_os, shuffle=True)
        hist_f2  = model.fit(ds_os, validation_data=ds_vl, epochs=15, callbacks=[cb_f2], verbose=0)
        epocas_f2_cv.append(len(hist_f2.history['loss']))

        hc = {}
        for key in hist_f1.history:
            hc[key] = hist_f1.history[key] + hist_f2.history.get(key, [])
        hc['val_macro_f1'] = ([np.nan] * len(hist_f1.history['loss']) + hist_f2.history.get('val_macro_f1', []))
        historiales.append(hc)

        preds = model.predict(X_val, batch_size=BATCH_SIZE, verbose=0)
        reg_raw = np.nan_to_num(tf.cast(preds[0], tf.float32).numpy().flatten(), nan=0.0)
        y_reg_pred_cv[val_idx]  = (reg_raw * psi_std) + psi_mean
        y_tend_pred_cv[val_idx] = np.argmax(np.nan_to_num(tf.cast(preds[1], tf.float32).numpy(), nan=0.0), axis=1)

        fold_models.append((model, scalers_fold, psi_mean, psi_std))

    # Hold-out y Ensemble
    X_ho, yr_ho, yt_ho, _, ph_ho = construir_dataset(df_holdout_in, features_list)
    X_ho = np.nan_to_num(X_ho, nan=0.0, posinf=0.0, neginf=0.0)

    ens_yr_preds, ens_yt_preds = [], []
    for fm, fs_fold, pm_fold, ps_fold in fold_models:
        X_ho_fold = escalar_externo(X_ho.copy(), fs_fold)
        p_fold = fm.predict(X_ho_fold, batch_size=BATCH_SIZE, verbose=0)
        yr_f = (np.nan_to_num(tf.cast(p_fold[0], tf.float32).numpy().flatten(), nan=0.0) * ps_fold) + pm_fold
        yt_f = tf.cast(p_fold[1], tf.float32).numpy()
        ens_yr_preds.append(yr_f)
        ens_yt_preds.append(yt_f)

    yr_pred_ens  = np.mean(ens_yr_preds, axis=0)
    yr_std_ens   = np.std(ens_yr_preds,  axis=0)
    yt_pred_ens  = np.argmax(np.mean(ens_yt_preds, axis=0), axis=1)

    metricas_ens = calcular_metricas_pk(yr_ho, yr_pred_ens)
    f1_ens  = f1_score(yt_ho, yt_pred_ens, average='macro', zero_division=0)
    bac_ens = balanced_accuracy_score(yt_ho, yt_pred_ens)

    print(f"\n   ► HO (ensemble): MAE={metricas_ens['MAE']:.4f} R²={metricas_ens['R2']:.4f} F1={f1_ens:.4f}")

    return {
        'label': label,
        'mae_ens': metricas_ens['MAE'],
        'rmse_ens': metricas_ens['RMSE'],
        'r2_ens': metricas_ens['R2'],
        'f1_ens': f1_ens,
        'bac_ens': bac_ens,
        'incert_ens_media': float(yr_std_ens.mean()),
        'semilla': SEMILLA
    }

# ==============================================================================
# CARGA DE DATOS Y EJECUCIÓN PRINCIPAL
# ==============================================================================
if __name__ == '__main__':
    print("\n📥 Cargando datos...")

    if not os.path.exists(ARCHIVO):
        print(f"❌ Error: No se encuentra el archivo en {ARCHIVO}. Crea la carpeta 'datos' y pon el CSV ahí.")
        exit(1)

    df = pd.read_csv(ARCHIVO, low_memory=False)
    if 'SEXO' in df.columns:
        df['SEXO_NUM'] = np.where(df['SEXO'] == 'MASCULINO', 1, 0)

    COLS_REQUERIDAS = ['EDAD', 'PESO', 'ESTATURA', 'SEXO_NUM', 'FC', 'PAM', 'INF', 'INF2', 'EFF', 'EFF2', 'PSI', 'ID_ANONIMO', 'FASE']
    df = df.dropna(subset=COLS_REQUERIDAS)

    # Separar Hold-out
    todos = df['ID_ANONIMO'].unique()
    np.random.shuffle(todos)
    n_ho      = max(1, int(len(todos) * 0.15))
    ids_ho    = todos[:n_ho]
    ids_cv    = todos[n_ho:]
    df_cv     = df[df['ID_ANONIMO'].isin(ids_cv)].copy()
    df_holdo  = df[df['ID_ANONIMO'].isin(ids_ho)].copy()

    # Downsampling
    df_cv    = df_cv.groupby('ID_ANONIMO', group_keys=False).apply(lambda g: g.iloc[::5]).copy()
    df_holdo = df_holdo.groupby('ID_ANONIMO', group_keys=False).apply(lambda g: g.iloc[::5]).copy()

    # Feature Engineering
    df_cv    = df_cv.groupby('ID_ANONIMO', group_keys=False).apply(agregar_features_eff).reset_index(drop=True)
    df_holdo = df_holdo.groupby('ID_ANONIMO', group_keys=False).apply(agregar_features_eff).reset_index(drop=True)
    df_cv['FASE_PROXY'] = df_cv['FASE']
    df_holdo['FASE_PROXY'] = df_holdo['FASE']

    df_cv_filtrado = filtrar_mantenimiento_redundante(df_cv, umbral_var=0.5, ventana=12)

    resultados_runs = []
    for i_run, semilla_run in enumerate(range(SEMILLA, SEMILLA + N_RUNS), start=1):
        configurar_semilla(semilla_run)
        res_run = run_experimento(FEATURES_V5, f'V5_run{i_run:02d}', df_cv_filtrado, df_holdo, CARPETA_FINAL)
        resultados_runs.append(res_run)

    print(f"\n✅ Entrenamiento completado. Resultados guardados en {CARPETA_FINAL}")